name: Build and deploy Zola site
on:
  push:
    branches:
      - action-testing

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ZOLA_VERSION: "latest/edge"
      ZOLA_CHECK: false
      ZOLA_CHECK_FLAGS: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Configure runner environment
        run: sudo snap install zola --channel=${{ env.ZOLA_VERSION }}
      
      - name: Check Zola project
        if: env.ZOLA_CHECK == true
        run: zola check ${{ env.ZOLA_CHECK_FLAGS }}

      - name: Build Zola site files
        run: zola build

      - name: Upload Github Pages artifact
        id: deployment
        uses: actions/upload-pages-artifact@v5
        with:
          path: public/
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v5
      
